pipeline {
    agent any
    stages {
        stage('git repo'){
            steps{
                bat "git clone https://github.com/pungcs12/UITest_palemo.git"
            }
        }
        stage ('Install Dependencies') {
            steps {
                script {
                    docker.image('python:3.7').inside {
                        sh '''
                            python3 --version
                            pip3 install --upgrade pip
                            pip3 install -r requirement.txt
                        '''
                    }
                }
            }
        }
    }
}