pipeline {
    agent any
    stages {
        stage('git repo'){
            steps{
                cleanWs()
                bat "git clone https://github.com/pungcs12/UITest_palemo.git"
            }
        }
        stage ('Install Dependencies') {
            steps {
                echo 'testing'
                bat label: '', script:'pip list'
                bat label: '', script:'python --version'
                bat label: '', script:'robot -d results UITest/myShoppingPage.robot'
                // script{
                //     sh '''
                //         ls
                //     '''
                // }
            }
        }
    }
}