pipeline {
    agent any
    stages {
        stage('git repo'){
            steps{
                cleanWs()
                bat "git clone https://github.com/pungcs12/UITest_palemo.git"
            }
        }
        stage ('Install Dependencies') {
            steps {
               script {
                   pip list
                    // docker.image('python:3.7').inside {
                    //     sh '''
                    //         // python3 --version
                    //         // cd jp-test/PerformanceTest
                    //         // python3 -m venv pref_test_venv
                    //         // . ./pref_test_venv/bin/activate
                    //         // pip3 install --upgrade pip
                    //         // pip3 install boto3
                    //         // pip3 install xmltodict
                    //         // pip3 install yattag
                    //         // pip3 install simplejson
                    //         // pip3 install pandas
                    //         // pip3 install xlrd==1.2.0
                    //         // pip3 install XlsxWriter
                    //         // pip3 install openpyxl
                    //     '''
                    // }
                }
            }
        }
    }
}